### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by Dagmawit-Al**
Setup Settings page

### CODE REVIEW

**Comment by vladislavmatygin** [comment]
Could you please investigate https://developer.apple.com/documentation/xcode/localization and add localization file in you Project ?
I would prefer to use https://swiftpackageindex.com/mac-cain13/R.swift
You can also use this library for UIColor, UIImage

**Comment by vladislavmatygin** [comment]
have you already handled changing of the root controller to not show login page to authorized users?

**Comment by vladislavmatygin** [comment]
General:
- enter after "super.viewDidLoad()"
- enter after "guard let ..."
- you implemented  R.swift, but why didn't you use it for strings, segues ?
- remove comments

class ForgotPasswordViewController :
- make [weak self] in sendPasswordReset function

class NewPasswordViewController :
- is "@IBAction func setPasswordPressed" necessarily?

**Comment by Dagmawit-AHG** [comment]
> General:
> 
> * enter after "super.viewDidLoad()"
> * enter after "guard let ..."
> * you implemented  R.swift, but why didn't you use it for strings, segues ?
> * remove comments
> 
> class ForgotPasswordViewController :
> 
> * make [weak self] in sendPasswordReset function
> 
> class NewPasswordViewController :
> 
> * is "@IBAction func setPasswordPressed" necessarily?

done

**Comment by vladislavmatygin** [comment]
You can merge 👍

**Comment by Dagmawit-AHG** [comment]
> You can merge 👍

Done 👍

**Comment by vladislavmatygin** [comment]
You can also "Delete branch", it is not a problem in this project, just let you know

**Pull request merged**
